<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modules')->delete();
        
        \DB::table('modules')->insert(array (
            0 => 
            array (
                'id' => 1,
                'panel' => 'Backend',
                'title' => 'Dashboard',
                'controller' => 'dashboard',
                'action' => 'index',
                'icon' => 'fas fa-tachometer-alt',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-18 06:23:47',
                'created_at' => '2021-11-17 05:20:46',
                'updated_at' => '2021-11-22 05:44:00',
            ),
            1 => 
            array (
                'id' => 2,
                'panel' => 'Backend',
                'title' => 'Admin Management',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-users-cog',
                'functionality' => 'other',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-17 06:16:16',
                'created_at' => '2021-11-17 05:21:21',
                'updated_at' => '2022-02-13 07:23:25',
            ),
            2 => 
            array (
                'id' => 3,
                'panel' => 'Backend',
                'title' => 'Modules',
                'controller' => 'modules',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-18 06:24:34',
                'created_at' => '2021-11-17 05:21:38',
                'updated_at' => '2021-11-18 06:24:34',
            ),
            3 => 
            array (
                'id' => 4,
                'panel' => 'Backend',
                'title' => 'Permission',
                'controller' => 'permission',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-17 06:53:25',
                'created_at' => '2021-11-17 05:22:14',
                'updated_at' => '2021-11-22 05:54:10',
            ),
            4 => 
            array (
                'id' => 5,
                'panel' => 'Backend',
                'title' => 'Role',
                'controller' => 'role',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-17 06:53:35',
                'created_at' => '2021-11-17 05:22:51',
                'updated_at' => '2021-11-22 05:39:18',
            ),
            5 => 
            array (
                'id' => 6,
                'panel' => 'Backend',
                'title' => 'Templates',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-envelope-open-text',
                'functionality' => 'other',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => NULL,
                'created_at' => '2021-11-17 07:33:07',
                'updated_at' => '2021-11-17 07:33:07',
            ),
            6 => 
            array (
                'id' => 7,
                'panel' => 'Backend',
                'title' => 'Email Templates',
                'controller' => 'emailtemplates',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 6,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-18 06:23:57',
                'created_at' => '2021-11-17 07:33:53',
                'updated_at' => '2021-12-07 10:39:17',
            ),
            7 => 
            array (
                'id' => 8,
                'panel' => 'Backend',
                'title' => 'Settings',
                'controller' => 'settings',
                'action' => 'index',
                'icon' => 'fas fa-cog',
                'functionality' => 'crud',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-19 05:42:58',
                'created_at' => '2021-11-18 09:11:22',
                'updated_at' => '2021-11-22 05:39:55',
            ),
            8 => 
            array (
                'id' => 9,
                'panel' => 'Backend',
                'title' => 'Custom Pages',
                'controller' => 'custompages',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 6,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 03:08:02',
                'created_at' => '2021-11-18 09:14:49',
                'updated_at' => '2022-02-13 03:08:02',
            ),
            9 => 
            array (
                'id' => 10,
                'panel' => 'Backend',
                'title' => 'Admin User',
                'controller' => 'user',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 2,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2021-11-19 06:45:13',
                'created_at' => '2021-11-19 04:26:20',
                'updated_at' => '2022-02-13 07:23:43',
            ),
            10 => 
            array (
                'id' => 11,
                'panel' => 'Backend',
                'title' => 'Language',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-list',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:08:35',
                'created_at' => '2022-02-13 06:08:35',
                'updated_at' => '2022-02-13 06:47:43',
            ),
            11 => 
            array (
                'id' => 12,
                'panel' => 'Backend',
                'title' => 'Location',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-map-marker-alt',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:12:02',
                'created_at' => '2022-02-13 06:12:02',
                'updated_at' => '2022-02-13 06:48:30',
            ),
            12 => 
            array (
                'id' => 13,
                'panel' => 'Backend',
                'title' => 'Category',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-list-alt',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:13:18',
                'created_at' => '2022-02-13 06:13:18',
                'updated_at' => '2022-02-13 06:13:18',
            ),
            13 => 
            array (
                'id' => 14,
                'panel' => 'Backend',
                'title' => 'General',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-user-tag',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:15:24',
                'created_at' => '2022-02-13 06:15:24',
                'updated_at' => '2022-02-13 06:49:23',
            ),
            14 => 
            array (
                'id' => 15,
                'panel' => 'Backend',
                'title' => 'Manage Posts',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-clipboard-list-check',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:17:55',
                'created_at' => '2022-02-13 06:17:55',
                'updated_at' => '2022-02-13 06:18:14',
            ),
            15 => 
            array (
                'id' => 16,
                'panel' => 'Backend',
                'title' => 'Manage Events',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-calendar-alt',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:53:09',
                'created_at' => '2022-02-13 06:53:09',
                'updated_at' => '2022-02-13 06:53:09',
            ),
            16 => 
            array (
                'id' => 17,
                'panel' => 'Backend',
                'title' => 'Manage Books',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-book',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 06:53:57',
                'created_at' => '2022-02-13 06:53:57',
                'updated_at' => '2022-02-13 06:53:57',
            ),
            17 => 
            array (
                'id' => 18,
                'panel' => 'Backend',
                'title' => 'Pages',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-file-alt',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 07:02:32',
                'created_at' => '2022-02-13 07:02:32',
                'updated_at' => '2022-02-13 07:02:32',
            ),
            18 => 
            array (
                'id' => 19,
                'panel' => 'Backend',
                'title' => 'Users',
                'controller' => '',
                'action' => '',
                'icon' => 'fas fa-user',
                'functionality' => 'none',
                'type' => 'Menu',
                'parent_menu_id' => NULL,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:33:06',
                'created_at' => '2022-02-13 11:33:06',
                'updated_at' => '2022-02-13 11:33:06',
            ),
            19 => 
            array (
                'id' => 20,
                'panel' => 'Backend',
                'title' => 'Country',
                'controller' => 'country',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:34:43',
                'created_at' => '2022-02-13 11:34:43',
                'updated_at' => '2022-02-13 11:34:43',
            ),
            20 => 
            array (
                'id' => 21,
                'panel' => 'Backend',
                'title' => 'State',
                'controller' => 'state',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:35:19',
                'created_at' => '2022-02-13 11:35:19',
                'updated_at' => '2022-02-13 11:35:19',
            ),
            21 => 
            array (
                'id' => 22,
                'panel' => 'Backend',
                'title' => 'District',
                'controller' => 'district',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:43:26',
                'created_at' => '2022-02-13 11:43:26',
                'updated_at' => '2022-02-13 11:43:26',
            ),
            22 => 
            array (
                'id' => 23,
                'panel' => 'Backend',
                'title' => 'SubDistrict',
                'controller' => 'subdistrict',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:44:05',
                'created_at' => '2022-02-13 11:44:05',
                'updated_at' => '2022-02-13 11:44:05',
            ),
            23 => 
            array (
                'id' => 24,
                'panel' => 'Backend',
                'title' => 'Block',
                'controller' => 'block',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:54:00',
                'created_at' => '2022-02-13 11:54:00',
                'updated_at' => '2022-02-13 11:54:09',
            ),
            24 => 
            array (
                'id' => 25,
                'panel' => 'Backend',
                'title' => 'Village',
                'controller' => 'village',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 12,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:55:01',
                'created_at' => '2022-02-13 11:55:01',
                'updated_at' => '2022-02-13 11:55:01',
            ),
            25 => 
            array (
                'id' => 26,
                'panel' => 'Backend',
                'title' => 'Department',
                'controller' => 'department',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 13,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:57:12',
                'created_at' => '2022-02-13 11:57:12',
                'updated_at' => '2022-03-05 16:09:10',
            ),
            26 => 
            array (
                'id' => 27,
                'panel' => 'Backend',
                'title' => 'Category',
                'controller' => 'category',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 13,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 11:59:14',
                'created_at' => '2022-02-13 11:59:14',
                'updated_at' => '2022-03-05 16:09:29',
            ),
            27 => 
            array (
                'id' => 28,
                'panel' => 'Backend',
                'title' => 'Festival',
                'controller' => 'festival',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 14,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 12:43:17',
                'created_at' => '2022-02-13 12:43:17',
                'updated_at' => '2022-02-13 12:43:49',
            ),
            28 => 
            array (
                'id' => 29,
                'panel' => 'Backend',
                'title' => 'Caste',
                'controller' => 'caste',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 14,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 12:44:09',
                'created_at' => '2022-02-13 12:44:09',
                'updated_at' => '2022-02-13 12:44:09',
            ),
            29 => 
            array (
                'id' => 30,
                'panel' => 'Backend',
                'title' => 'Religion',
                'controller' => 'religion',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 14,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-13 12:46:11',
                'created_at' => '2022-02-13 12:46:11',
                'updated_at' => '2022-02-13 12:46:11',
            ),
            30 => 
            array (
                'id' => 31,
                'panel' => 'Backend',
                'title' => 'Relation',
                'controller' => 'relation',
                'action' => 'index',
                'icon' => 'far fa-circle',
                'functionality' => 'crud',
                'type' => 'Submenu',
                'parent_menu_id' => 14,
                'parent_submenu_id' => NULL,
                'menu_position' => NULL,
                'submenu_position' => NULL,
                'is_hiddden' => '0',
                'is_active' => '1',
                'is_active_at' => '2022-02-14 02:31:34',
                'created_at' => '2022-02-14 02:31:34',
                'updated_at' => '2022-02-14 02:31:34',
            ),
        ));
        
        
    }
}